/* eslint-disable @next/next/no-sync-scripts */
"use client";
import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import ThemeButton from "@/components/ThemeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </head>
      <Providers>
        <body className={`${inter.className} mx-5`}>
          <header>
          
            <Navbar />
          </header>

          <main>
            
            {children}
          </main>

          <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
          <script>AOS.init();</script>
        </body>
      </Providers>
    </html>
  );
}
